name: Manual Sync & Pack workflow

# i hate dependabot for limited token :/
permissions:
  id-token: write
  contents: write
  actions: write
  checks: write
  deployments: write
  discussions: write
  issues: write
  pages: read
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
  workflows: write

on:
  pull_request:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  syncandpack:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Run actions script
        run: ./actions_pack.sh
      # holy crap
      - name: Checkout PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr checkout ${{ github.event.number }}
        if: github.ref != 'refs/heads/main' && github.event_name == 'pull_request'
      - name : Commit changes to main branch
        run: git push
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'

        
